### ISSUE TITLE
Spinner along with an ongoing process

### ISSUE THREAD

**Issue by AnirudhG07** [petereon/beaupy#111]
Is there a way to integrate the spinner along with an ongoing process, say a process takes some time. If there could be a way i could tell start now, and end now. Like i am doing some math which is taking 5-6 seconds, start the spinner when the calculations start and end when i get the output.
There exists multithreading for it, but my code becomes a bit ugly when i do it.
Is there a better way of doing this in `beaupy` or can it be added as a new feat?

If this issue has already been raised somewhere I might have skipped, please do refer to it. Thanks!

**Comment by petereon** [comment]
Hi @AnirudhG07, I might be misunderstanding the question, but doesn't that work already?

Considering the `example.py`:
https://github.com/petereon/beaupy/blob/95d8b9298728d437a19f8bacf28ec24ff2a51368/example.py#L42-L46

`spinner.start()` call is non-blocking, the spinner starts running in a separate thread and should run independently on what you do in a main thread - though there might be edge cases due to how Python handles threading.

The expected behaviour is that the spinner runs until you call `spinner.stop()` independent on what you do in between. If it doesn't, then that is a bug.

**Comment by AnirudhG07** [comment]
We are here setting the time ourselves, but i donot know how much time my tasks take, since it varies with inputs.

**Comment by AnirudhG07** [comment]
Oh wait, so instead of time.sleep, i can just put my process there and it should work right. my bad. Just confirm once.

**Comment by petereon** [comment]
Right, so if my understanding is correct you are doing work in a thread - not blocking the main thread - so the spinner immediately exists.

Well the simplest solution is just doing the work that takes time in the main thread instead of `time.sleep()`. I use the sleep in the example as a stand-in for some actual heavy work. So something like following should also work:

```
spinner.start()

result = some_heavy_math_that_takes_a_long_time()

spinner.stop()
```

**Comment by AnirudhG07** [comment]
Sorry for the stupid issue, i donno why i didnt think of that. Thanks so much!

**Comment by petereon** [comment]
No worries, happy to help!
