### ISSUE TITLE
Prompt does not bash complete

### ISSUE THREAD

**Issue by juxeii** [petereon/beaupy#49]
Hi,

it would be helpful if there is support for bash completion(an option for [prompt](https://petereon.github.io/beaupy/api/#prompt) would be enough).
For example, if I want that the user inputs a file path, it would be helpful if he could hit tab and get a path completion.

**Comment by petereon** [comment]
Hi @juxeii ,

thanks for a feature request. It's a great idea. Sounds like it would be reasonably easy to implement too. I am very open to Pull Requests if you are technical and would like to take a stab at it. 

Otherwise I'll take it upon myself, but it will take some time as I am currently jugging a bit more stuff than I'd like to.

**Comment by juxeii** [comment]
Take your time :)
